name: "build-project"
description: "Composite action to create an executable with corresponding files. Works for any platform."

inputs:
  tag:
    description: 'Tag version for the release'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up the environment
      uses: ./.github/actions/setup-poetry-env

    - name: Install extra Linux system dependencies for PySide6
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libxcb-icccm4 \
          libxkbcommon-x11-0 \
          libxcb-render-util0 \
          libxcb-keysyms1 \
          libxcb-shape0 \
          libxcb-image0
      shell: bash

    - name: Build executable - PyInstaller
      uses: sayyid5416/pyinstaller@v1
      with:
        spec: "main.py"
        upload_exe_with_name: "HPM ${{ inputs.tag }}"
        options: -w, --name "HPM ${{ inputs.tag }}", --icon "Houdini_Package_Manager/resources/icons/hpm.ico",

    - name: Verify built files for Linux
      run: ls -R dist/
      shell: bash
