name: build-test

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Install extra system dependencies for PySide6
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxcb-icccm4 \
            libxkbcommon-x11-0 \
            libxcb-render-util0 \
            libxcb-keysyms1 \
            libxcb-shape0 \
            libxcb-image0

      - name: Export tag
        id: vars
        run: echo tag=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT

      # - name: Build executable - PyInstaller
      #   uses: sayyid5416/pyinstaller@v1
      #   with:
      #     python_ver: '3.11'
      #     spec: 'main.py'
      #     requirements: 'requirements.txt'
      #     upload_exe_with_name: 'HPM 9.9.9'
      #     options: --name "HPM 9.9.9", --icon "Houdini_Package_Manager/resources/icons/hpm.ico"

      - name: Build exe
        run: |
          pip install pyinstaller
          pyinstaller main.py

      - name: Verify built files
        run: ls -R dist/
