name: release-main

on:
  release:
    types: [published]
    branches: [main]

jobs:
  
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Export tag
        id: vars
        run: echo tag=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT

      - name: Build executable with PyInstaller
        run: |
          poetry run pyinstaller -w \
            --name="HPM ${{ steps.vars.outputs.tag }}" \
            --icon="Houdini_Package_Manager/resources/icons/hpm.ico" \
            main.py
      
      - name: Compress executable
        run: python -c "import shutil; shutil.make_archive('dist/HPM ${{ steps.vars.outputs.tag }}', 'zip', 'dist/HPM ${{ steps.vars.outputs.tag }}')"

      - name: Upload build to release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "dist/HPM ${{ steps.vars.outputs.tag }}.zip"
          asset_name: "HPM ${{ steps.vars.outputs.tag }}.zip"
          asset_content_type: application/zip
      
      - name: Build and publish to PyPI
        run: |
          source .venv/bin/activate
          poetry version $RELEASE_VERSION
          make build-and-publish
        env: 
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
