name: release-main

on:
  push:
    branches: [main]

  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Tag version for this release'
        required: true
        default: 'x.y.z'

jobs:
  
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Export tag
        id: vars
        run: echo tag=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build executable with PyInstaller
        run: |
          poetry run pyinstaller -w \
            --name="HPM ${{ steps.vars.outputs.tag }}" \
            --icon="Houdini_Package_Manager/resources/icons/hpm.ico" \
            main.py
      
      - name: Compress executable
        run: python -c "import shutil; shutil.make_archive('dist/HPM ${{ steps.vars.outputs.tag }}', 'zip', 'dist/HPM ${{ steps.vars.outputs.tag }}')"

      - name: Upload build to release assets
        uses: actions/upload-artifact@v4
        with:
          name: "HPM ${{ steps.vars.outputs.tag }}.zip"
          path: "dist/HPM ${{ steps.vars.outputs.tag }}.zip"
      
      - name: Build and publish to PyPI
        run: |
          source .venv/bin/activate
          poetry version $RELEASE_VERSION
          make build-and-publish
        env: 
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
